Sign up and Login Page working with db/backend skeleton
GoblinSharkTeam/MyBookClub pull request #5
Opened 2022-03-31 04:44 UTC by nidhikay

- Create Frontend Sign up page  and Login screen and get it hooked up to backend working as well as hooked up to db

Evidence of Sign up working:
<img width="658" alt="SignupPage" src="https://user-images.githubusercontent.com/44415609/160978033-126e8e6b-7027-4ce8-9527-7727efe1927c.png">

Database showing user has been added successfully:
<img width="813" alt="DBnewuser" src="https://user-images.githubusercontent.com/44415609/160978039-5c098153-484a-4cbf-a236-c5c7a1ba2074.png">

Evidence of Login working - Happy Path working 
<img width="1092" alt="Screen Shot 2022-03-30 at 9 43 09 PM" src="https://user-images.githubusercontent.com/44415609/160978133-0b016e0d-1eba-4450-894c-8c75074e0607.png">

2022-03-31 18:04 UTC, jonathanhaviv requested changes
See comments for requested changes.

2022-03-31 18:04 UTC, jonathanhaviv commented on client/App.jsx
> +    axios.post('http://localhost:3000/users/signup', {
This should post to localhost:8080 when in dev. The dev-server will proxy to this. And should remove the need for cors.

2022-03-31 18:04 UTC, jonathanhaviv commented on server/routes/users.js
> +  const username = req.body.username;
Would recommend destructuring to make the code cleaner, but not necessary. Also, move this middleware to a userController file.

2022-03-31 18:04 UTC, jonathanhaviv commented on client/App.jsx
> +        <label>Firstname</label>
Can you update labels to have the correct htmlFor for each label?

2022-04-01 01:14 UTC, jonathanhaviv approved these changes

2022-04-01 01:16 UTC, feiw101 approved these changes

2022-04-01 01:18 UTC, merged